# Interactive setup for the Meta Ads Dashboard (Windows / PowerShell).
# Prompts for Meta API credentials, writes them to dashboard/.env,
# and verifies the connection against the Meta Graph API.
#
# Usage: powershell -ExecutionPolicy Bypass -File scripts\setup.ps1

$ErrorActionPreference = 'Stop'

$ProjectRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$EnvFile = Join-Path $ProjectRoot 'dashboard\.env'
$GraphVersion = 'v21.0'

Write-Host ""
Write-Host "=== Meta Ads Dashboard - Setup ===" -ForegroundColor Cyan
Write-Host ""

if (Test-Path $EnvFile) {
    Write-Host "An existing dashboard\.env was found."
    $reply = Read-Host "Overwrite it? (y/N)"
    if ($reply -notmatch '^(y|Y|yes|YES)$') {
        Write-Host "Aborted. Nothing changed."
        exit 0
    }
}

$MetaToken     = Read-Host "Meta Access Token"
$MetaAppSecret = Read-Host "Meta App Secret"
$MetaAppId     = Read-Host "Meta App ID (optional, press Enter to skip)"

if ([string]::IsNullOrWhiteSpace($MetaToken) -or [string]::IsNullOrWhiteSpace($MetaAppSecret)) {
    Write-Error "Access token and app secret are both required."
    exit 1
}

# Ensure destination directory exists
$EnvDir = Split-Path -Parent $EnvFile
if (-not (Test-Path $EnvDir)) {
    New-Item -ItemType Directory -Path $EnvDir | Out-Null
}

$stamp = Get-Date -Format 'yyyy-MM-dd HH:mm'
@"
# Meta Ads API Credentials
# Generated by scripts\setup.ps1 on $stamp
# Do not commit this file.
META_ACCESS_TOKEN=$MetaToken
META_APP_SECRET=$MetaAppSecret
META_APP_ID=$MetaAppId
"@ | Set-Content -Path $EnvFile -Encoding UTF8

Write-Host ""
Write-Host "Credentials written to dashboard\.env" -ForegroundColor Green

Write-Host "Verifying connection to Meta Graph API..."
$Uri = "https://graph.facebook.com/$GraphVersion/me/adaccounts"
try {
    $response = Invoke-RestMethod -Uri $Uri -Method Get -Body @{
        access_token = $MetaToken
        fields       = 'name,account_id,account_status'
        limit        = 3
    }
} catch {
    Write-Error "Error from Meta API: $($_.Exception.Message)"
    Write-Host "Check your token at https://developers.facebook.com/tools/explorer/"
    exit 1
}

Write-Host ""
Write-Host "Connection successful. First ad accounts visible to this token:" -ForegroundColor Green
$response.data | Format-Table -AutoSize

Write-Host "Done. Start the dashboard with:"
Write-Host "  cd dashboard; npm install; npm run dev"
Write-Host ""
