#!/usr/bin/env bash
# Interactive setup for the Meta Ads Dashboard.
# Prompts for Meta API credentials, writes them to dashboard/.env,
# and verifies the connection against the Meta Graph API.
#
# Usage: bash scripts/setup.sh

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/dashboard/.env"
GRAPH_VERSION="v21.0"

printf "\n=== Meta Ads Dashboard — Setup ===\n\n"

if [ -f "$ENV_FILE" ]; then
    printf "An existing dashboard/.env was found.\n"
    read -r -p "Overwrite it? (y/N): " REPLY
    case "$REPLY" in
        y|Y|yes|YES) ;;
        *) printf "Aborted. Nothing changed.\n"; exit 0 ;;
    esac
fi

read -r -p "Meta Access Token: " META_TOKEN
read -r -p "Meta App Secret: " META_APP_SECRET
read -r -p "Meta App ID (optional, press Enter to skip): " META_APP_ID

if [ -z "${META_TOKEN:-}" ] || [ -z "${META_APP_SECRET:-}" ]; then
    printf "\nError: access token and app secret are both required.\n" >&2
    exit 1
fi

# Write dashboard/.env
mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Meta Ads API Credentials
# Generated by scripts/setup.sh on $(date '+%Y-%m-%d %H:%M')
# Do not commit this file.
META_ACCESS_TOKEN=$META_TOKEN
META_APP_SECRET=$META_APP_SECRET
META_APP_ID=${META_APP_ID:-}
EOF
chmod 600 "$ENV_FILE" 2>/dev/null || true

printf "\nCredentials written to dashboard/.env\n"

# Test connectivity
printf "Verifying connection to Meta Graph API...\n"
RESPONSE="$(curl -sS -G \
    --data-urlencode "access_token=$META_TOKEN" \
    --data-urlencode "fields=name,account_id,account_status" \
    --data-urlencode "limit=3" \
    "https://graph.facebook.com/$GRAPH_VERSION/me/adaccounts")"

if printf "%s" "$RESPONSE" | grep -q '"error"'; then
    printf "\nError from Meta API:\n%s\n" "$RESPONSE" >&2
    printf "\nCheck your token at https://developers.facebook.com/tools/explorer/\n" >&2
    exit 1
fi

printf "\nConnection successful. First ad accounts visible to this token:\n"
printf "%s\n" "$RESPONSE" | python3 -m json.tool 2>/dev/null || printf "%s\n" "$RESPONSE"

printf "\nDone. Start the dashboard with:\n"
printf "  cd dashboard && npm install && npm run dev\n\n"
